// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
//
// 生成命令：pnpm contracts:generate
// 真源：src-tauri/src/domain/types.rs 与 src-tauri/src/domain/errors.rs
// 手工修改本文件会导致 `pnpm contracts:check` 失败。

/** 应用内标识。UUID 字符串。不等同于 Windows 文件身份，也不等同于内容哈希。 */
export type Id = string

/** 相对路径以组件数组表示，例如 ["学习", "数学", "第三章.pdf"]。 */
export type RelPath = Array<string>

export type Mode = "rules" | "aiLocal" | "aiCloud";

export type Risk = "info" | "warning" | "block";

export type ExtractionStatus = "pending" | "ok" | "partial" | "unsupported" | "failed";

export type TaskStatus = "queued" | "running" | "completed" | "partial" | "failed" | "cancelled" | "recoveryRequired";

export type RunStatus = "queued" | "running" | "completed" | "partial" | "failed" | "cancelled" | "recoveryRequired";

export type OpStatus = "pending" | "prepared" | "applied" | "failed" | "skipped" | "ambiguous";

export type OpResolution = "open" | "acknowledged";

export type UndoStatus = "notRequested" | "prepared" | "undone" | "conflict";

export type PlanStatus = "draft" | "validated" | "sealed" | "archived";

export type PlanAction = "move" | "noop";

export type PlanItemOrigin = "rule" | "ai" | "user";

export type Fingerprint = { volumeId: string, 
/**
 * Windows 文件身份（卷内唯一）。不等同于路径。
 */
fileId: string, 
/**
 * 十进制字符串，避免 JavaScript 数值精度损失。
 */
size: string, 
/**
 * UTC 纳秒时间戳，十进制字符串。
 */
modifiedNs: string, 
/**
 * 生成**可执行计划**时必须为 `Some`。仅用于展示的初扫结果可以为 `None`。
 */
sha256: string | null, };

export type FileRecord = { id: string, scanId: string, rootId: string, relativePath: Array<string>, extension: string, fingerprint: Fingerprint, extractionStatus: ExtractionStatus, 
/**
 * 跳过原因代码；`None` 表示未被跳过。
 */
skipCode: string | null, };

export type Evidence = { 
/**
 * 例如 `page:1`、`chars:0-120`。必须来自本次真实提取结果，不接受模型自造引用。
 */
locator: string, excerpt: string, };

export type Extraction = { fileId: string, 
/**
 * 提取时同一只读句柄对应的快照，用于证明读取期间文件稳定。
 */
sourceFingerprint: Fingerprint, status: ExtractionStatus, 
/**
 * **仅内存或会话临时缓存**，不写持久日志。
 */
text: string, evidence: Array<Evidence>, truncated: boolean, 
/**
 * 失败或降级原因代码。
 */
code: string | null, };

export type Proposal = { fileId: string, 
/**
 * 根目录下至多两层目录，每项只是一个目录名称（不含分隔符）。
 */
category: Array<string>, 
/**
 * 不含扩展名、绝对路径或路径分隔符。扩展名由程序从真实源名附加。
 */
stem: string, reason: string, confidence: number, evidenceLocator: string | null, };

export type PlanItem = { id: string, fileId: string, source: Array<string>, target: Array<string>, action: PlanAction, selected: boolean, origin: PlanItemOrigin, reason: string, 
/**
 * 生成计划时绑定的源文件指纹。执行前必须重新核对，不一致即停止。
 */
expected: Fingerprint, };

export type Plan = { id: string, rootId: string, scanId: string, 
/**
 * 乐观锁版本。任何编辑都会 +1，并使旧校验与旧确认立即失效。
 */
revision: number, mode: Mode, status: PlanStatus, items: Array<PlanItem>, 
/**
 * UTC RFC3339 字符串。
 */
createdAt: string, };

export type Issue = { code: string, severity: Risk, 
/**
 * 与具体计划项相关时给出；全局问题为 `None`。
 */
itemId: string | null, message: string, };

export type ValidationReport = { planId: string, 
/**
 * 该报告对应的计划版本。与当前计划版本不一致即视为过期。
 */
revision: number, 
/**
 * 由后端对固定字段的规范序列化结果计算 SHA-256。
 */
digest: string, executableCount: number, issues: Array<Issue>, 
/**
 * 一次性令牌。**只有**后端能生成，前端不得自行生成或伪造。
 */
validationToken: string | null, 
/**
 * UTC RFC3339，最多 5 分钟有效。
 */
expiresAt: string | null, };

export type RunCounts = { applied: number, failed: number, skipped: number, pending: number, 
/**
 * 判定不出来、需要人工核对的项数（规格 8.3）。
 *
 * **单独计数而不是并进 `pending`**：界面上「还没轮到他」和
 * 「做了但说不清」需要不同的措辞和不同的动作，混在一起用户无从下手。
 */
ambiguous: number, };

export type RunReport = { runId: string, planId: string, 
/**
 * `apply`（整理）或 `undo`（撤销）。
 *
 * 历史列表**必须**能分清这两种记录：它们都会出现在同一条时间线上，
 * 而「已完成 3 项」在整理里是「搬走了 3 个文件」、在撤销里是
 * 「搬回了 3 个文件」——意思正好相反。少了这个字段，界面只能
 * 给撤销记录也挂一个「撤销」按钮，而那是一次注定被拒绝的点击。
 */
direction: string, 
/**
 * 当前操作事实与冲突集合的摘要，用于防止用户确认一份过期的报告。
 */
stateDigest: string, status: RunStatus, counts: RunCounts, issues: Array<Issue>, };

export type RecoveryItem = { operationId: string, itemId: string, source: Array<string>, target: Array<string>, status: OpStatus, resolution: OpResolution, 
/**
 * 为什么是这个判定。这句话会直接显示在界面上，写的是「用户能据以行动」的内容。
 */
message: string, };

export type RecoveryReport = { runId: string, planId: string, status: RunStatus, 
/**
 * **确认必须带上它**：两次读取之间只要有任意一项的状态或处置变了，
 * 摘要就会变，后端据此拒绝一份过期的确认。
 */
stateDigest: string, items: Array<RecoveryItem>, counts: RunCounts, 
/**
 * 仍有未决项没被处置时为 true —— 此时后端**禁止**新的执行任务。
 */
blocksNewRuns: boolean, 
/**
 * 该 run 的根目录在当前会话里是否仍被授权。
 *
 * 未授权的根换不回路径，核对根本无从下手。这时要**如实说明**，
 * 而不是回报一份「没有未决项」的空报告——那会让界面显示一切正常。
 */
rootAuthorized: boolean, };

export type BlockedRun = { runId: string, planId: string, 
/**
 * 还有几项没有被核对处置。
 */
unresolved: number, };

export type RecoveryStatus = { 
/**
 * 还有任何未处置的未决项时为 true —— 此时不能开始新任务（规格 8.2）。
 */
blocked: boolean, blockedRuns: Array<BlockedRun>, };

export type UndoOutcome = "ready" | "conflict" | "alreadyUndone";

export type UndoItem = { 
/**
 * 被撤销的那个原操作。
 */
operationId: string, itemId: string, 
/**
 * 撤销时的**源** = 原操作的目标位置。
 */
source: Array<string>, 
/**
 * 撤销时的**目标** = 原操作的源位置。
 */
target: Array<string>, outcome: UndoOutcome, 
/**
 * 是否被选中执行。`Conflict` 与 `AlreadyUndone` 初始为 false。
 */
selected: boolean, 
/**
 * 判定原因，直接显示在界面上。
 */
message: string, };

export type UndoPreview = { 
/**
 * 本次预览落库的撤销计划 id。执行时原样带回，用来消费一次性令牌。
 */
undoPlanId: string, originalRunId: string, 
/**
 * 当前撤销事实的摘要。执行时必须原样带回，变了就说明这一屏已经过期。
 */
digest: string, items: Array<UndoItem>, 
/**
 * 可安全撤销的项数。
 */
readyCount: number, 
/**
 * 有冲突的项数。
 */
conflictCount: number, 
/**
 * 已经撤销过的项数（重复撤销时它们不会再次被搬动）。
 */
alreadyUndoneCount: number, 
/**
 * 一次性令牌。**只有**后端能签发；前端不得自行生成。
 */
undoToken: string | null, 
/**
 * UTC RFC3339，最多 5 分钟有效。
 */
expiresAt: string | null, };

export type UndoReport = { 
/**
 * 本次撤销产生的 run（`direction = 'undo'`，可用 `get_run` 查询）。
 */
runId: string, originalRunId: string, status: RunStatus, 
/**
 * 已成功移回的项数。
 */
reverted: number, 
/**
 * 因冲突而保留现状的项数。
 */
conflicted: number, 
/**
 * 本次之前就已经撤销过、这次只是再次确认的项数。
 */
alreadyUndone: number, 
/**
 * 用户没选中、因而未处理的项数。
 */
untouched: number, items: Array<UndoItem>, 
/**
 * 目录清理失败等**不影响已移回文件事实**的告警。
 *
 * 单独一个列表而不是塞进 `items`：文件已经安全回去了，
 * 把「空目录没删掉」混进分项结果会让用户以为撤销失败了。
 */
warnings: Array<Issue>, };

export type AppError = { code: string, message: string, 
/**
 * 指明「重试一次可能成功」。为 `true` 时前端才显示重试入口。
 */
retryable: boolean, details: { [key in string]: string }, };

export type AppSettings = { mode: Mode, 
/**
 * 规格 6.1 默认值：最多 10,000 个普通文件。
 */
scanMaxFiles: number, 
/**
 * 规格 6.1 默认值：递归深度 20。
 */
scanMaxDepth: number, selectedProviderId: string | null, };

export type OcrAvailabilityReport = { 
/**
 * 用哪个变体：`available` / `noRecognizerLanguage` / `noChineseLanguage` / `unsupported`。
 */
status: string, 
/**
 * 可识别的语言标签。不可用时为空或列出已装但不含中文的语言。
 */
languages: Array<string>, 
/**
 * 给用户看的一句话，**必须包含下一步动作**。
 */
message: string, };

export type ProviderKind = "local" | "compatible";

export type ProviderSummary = { id: string, kind: ProviderKind, endpoint: string, model: string, hasCredential: boolean, };

export type ProviderProbe = { 
/**
 * 服务端回显的模型名。用户据此确认「我连的确实是我以为的那个模型」。
 */
model: string, 
/**
 * 这次探测是否拿到了**符合结构**的建议数组。
 *
 * 规格 6.4：「提供商的结构化输出能力需探测；即使服务端宣称保证 JSON，
 * 客户端仍必须校验。」这个布尔量就是那次校验的结果——
 * 它是**探测出来的**，不是读某个配置项读来的。
 */
structuredOutput: boolean, 
/**
 * 给用户的一句话，含下一步动作。
 */
message: string, };

export type DisclosurePreview = { 
/**
 * 这份载荷的摘要。`grant_disclosure` 用它换授权。
 */
payloadDigest: string, providerId: string, model: string, fileCount: number, characterCount: bigint, instruction: string, items: Array<DisclosureItemPreview>, };

export type DisclosureItemPreview = { fileId: string, fileName: string, characterCount: number, 
/**
 * 这段文本被裁剪过（原文更长）。
 *
 * 规格原话：「**文本裁剪不是隐私脱敏保证**」——它只是控制载荷大小。
 * 界面上要如实说明「被截过」，免得用户以为剩下的内容不会发出去。
 */
truncated: boolean, 
/**
 * 实际文本的开头。
 */
excerpt: string, 
/**
 * 这一项**有没有可发送的正文**，以及为什么没有。
 *
 * 少了它，界面只能显示「0 个字符」，而用户从那个数字里读不出
 * 该做什么：
 *
 * | 情况 | 用户该做的事 |
 * |---|---|
 * | 文件本来就没有文字 | 换一个文件 |
 * | 格式读不出文字（扫描型 PDF） | 找它的文字版 |
 * | **提取失败** | 重试，或者查这台机器上的解析环境 |
 * | 用户自己关掉了正文 | 没别的，就是他选的 |
 *
 * 把它们混成一句「没有正文」，用户会去检查一个完全正常的文件，
 * 或者白白放弃一个其实能用的文件。
 */
textStatus: DisclosureTextStatus, };

export type DisclosureTextStatus = "present" | "empty" | "unsupported" | "failed" | "excluded" | "pending";

export type DisclosureGrant = { consentId: string, payloadDigest: string, };

export type AnalysisStart = { 
/**
 * 后台任务的 id（与扫描共用同一套任务通道）。
 */
taskId: string, 
/**
 * 这次分析的 id。`create_plan` 用它取回建议。
 */
analysisId: string, };

export type RootSummary = { rootId: string, 
/**
 * 面向用户的原始路径（可能是长路径或含中文）。
 */
displayPath: string, 
/**
 * 卷标识。前端可利用它提示「根目录换了卷」。
 */
volumeId: string, };

export type ScanSummary = { 
/**
 * 规格 5.2：`start_scan` 返回 taskId。
 */
taskId: string, scanId: string, rootId: string, 
/**
 * 枚举到的条目总数（含被跳过的）。
 */
total: number, 
/**
 * 可参与整理的普通文件数。
 */
usable: number, 
/**
 * 被跳过的条目数。
 */
skipped: number, 
/**
 * 规格 6.1：达到数量/深度上限时为 true，界面必须要求缩小范围。
 */
truncated: boolean, };

export type FilePage = { items: Array<FileRecord>, 
/**
 * 下一页游标；为 `None` 表示已经是最后一页。
 *
 * 游标是**上一页最后一条记录的 id**，不是偏移量：
 * 偏移量在底层列表变化时会漏项或重复，id 不会。
 */
nextCursor: string | null, 
/**
 * 该 scan 下的条目总数，便于界面显示「x / total」。
 */
total: number, };

export type TaskError = { code: string, message: string, retryable: boolean, };

export type TaskSummary = { taskId: string, status: TaskStatus, processed: number, 
/**
 * 总量尚未确定时为 `null`。
 */
total: number | null, 
/**
 * 扫描类任务完成后的 scanId；其他任务为 `null`。
 */
scanId: string | null, 
/**
 * 失败时的结构化错误；成功或进行中为 `null`。
 *
 * 注意：`AppError` 在 `domain::errors` 里，这里用 `crate::domain::errors::AppError`
 * 会导致 types.rs 反向依赖 errors.rs。为避免循环，改用脱敏后的最小结构。
 */
error: TaskError | null, };

export type RuleKind = "byType" | "byMonth";

export type PlanItemEdit = { itemId: string, 
/**
 * 不修改勾选状态时传 `null`。
 */
selected: boolean | null, 
/**
 * 新的目标相对路径（组件数组）。不修改时传 `null`。
 */
target: Array<string> | null, };

export type PlanBuild = { plan: Plan, 
/**
 * 构建期间发现的问题。`Warning` 表示「这一项不可选，原因如下」。
 */
issues: Array<Issue>, };


/**
 * IPC 返回信封，对应 Rust 的 `IpcResult<T>`（src-tauri/src/domain/ipc.rs）。
 *
 * 它没有从 Rust 侧生成，原因是契约要求的是布尔量 `ok` 字段，
 * 而 serde 的 tag 机制只能生成变体名字符串。信封本身有单元测试保证形状。
 */
export type Result<T> = { ok: true; data: T } | { ok: false; error: AppError }
